"""Create release_number table

Revision ID: bfda31e29f81
Revises: b9e040316c1f
Create Date: 2021-10-28 11:14:59.434396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfda31e29f81'
down_revision = 'b9e040316c1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_number',
    sa.Column('rn', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rn')
    )
    op.drop_table('nasa_tabela')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nasa_tabela',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ime', sa.VARCHAR(), nullable=True),
    sa.Column('godina', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('release_number')
    # ### end Alembic commands ###
