"""Create issues_in_sheet and ignored_issues tables

Revision ID: d6fa4d488fc2
Revises: bfda31e29f81
Create Date: 2021-11-03 17:14:45.239272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6fa4d488fc2'
down_revision = 'bfda31e29f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ignored_issues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues_in_sheet',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues_in_sheet')
    op.drop_table('ignored_issues')
    # ### end Alembic commands ###
